In [1]:
import pandas as pd

In [3]:
student_info = {
    "name": ["bob", "alice", "mark"],
    "cgpa": [9.5, 8.75, 8]
}

df = pd.DataFrame(student_info)

print(df)

    name  cgpa
0    bob  9.50
1  alice  8.75
2   mark  8.00

In [7]:
# series
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

# index based access
print(s[0])
print(s[1])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
2

In [10]:
# labelled based access
s = pd.Series([23, 24, 25], index = ["adam", "eve", "bob"])
print(s)
print(s["adam"])
print(s["bob"])
print(s.index)

adam    23
eve     24
bob     25
dtype: int64
23
25
Index(['adam', 'eve', 'bob'], dtype='object')

In [13]:
# series properties
# vectorised operations
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
print(s1 + s2)

# mutable values, immutable size
s1[0] = 100
changed_s1 = s1.drop(0)
print(s1) # values are intact
print(changed_s1)

0     7
1     9
2    11
3    13
4    15
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
# dataframe
# creating dataframes
# dictionary of lists
student_info = {
    "name": ["bob", "alice", "mark"],
    "age": [25, 29, 31],
    "cgpa": [9.5, 8.75, 8]
}
df = pd.DataFrame(student_info)
print(df)

print(df.index)
print(df.columns)

    name  age  cgpa
0    bob   25  9.50
1  alice   29  8.75
2   mark   31  8.00
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'cgpa'], dtype='object')

In [15]:
df

    name  age  cgpa
0    bob   25  9.50
1  alice   29  8.75
2   mark   31  8.00

In [18]:
# list of lists
age_info = [["bob", 25], ["charlie", 30], ["mark", 18]]
df = pd.DataFrame(age_info, columns = ["name", "age"])
print(df)

      name  age
0      bob   25
1  charlie   30
2     mark   18

In [2]:
# using np arrays
import numpy as np
np_arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(np_arr, columns = ["a", "b", "c"])
print(df)

   a  b  c
0  1  2  3
1  4  5  6

In [3]:
# csv data
df = pd.read_csv("../data/employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [4]:
# json data
df = pd.read_json("../data/employee_data.json")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [14]:
# methods
print(df.head()) # starting 5 rows
print(df.tail()) # last 5 rows
print(df.sample()) # random sample
print(df.info()) # dataframe structure
print(df.shape)
print(df.describe()) # data summary
df.columns # column values
print(df.nunique()) # number of unique rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000
   ID   Name  Age Department  Salary
3   4  David   45  Marketing   91000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None
(10, 5)
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000
ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [15]:
# aqi data set
df = pd.read_csv("../data/global_air_quality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [19]:
# methods on air quality data
print(df.head()) 
print(df.describe())

                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250
3  2025-11-04 21:25:17.554219      US  New York    40.713    -74.006  30.403
4  2025-11-04 22:25:17.554219      US  New York    40.713    -74.006  21.083

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783
3   79.951  63.536  7.609  31.369  0.230  158       23.140    89.153
4   66.423  38.997  6.919  45.615  1.085   97       13.632    76.499

   wind_speed
0       3.725
1       8.969
2       9.650
3       8.956
4       4.017
           latitude     longitude          pm25          pm10           no2  \
count  18000.000000  18000.000000  18000.000000  18000.000000  18000.000000
mean      23.065980     37.655560     40.369131     70.152228     32.055176
std       26.156536     78.600701     17.647450     24.999440     13.820680
min      -37.814000   -123.121000      0.025000      0.061000      0.013000
25%       12.972000      2.352000     27.904500     53.125500     22.362500
50%       29.232000     42.146000     40.286500     69.961000     32.019500
75%       41.008000    103.820000     52.436250     87.256500     41.364250
max       60.170000    174.763000    115.683000    161.810000     90.019000

                so2            o3            co           aqi   temperature  \
count  18000.000000  18000.000000  18000.000000  18000.000000  18000.000000
mean       6.035508     48.065100      0.800595    104.645556     21.510251
std        2.454790     14.950849      0.250254     25.616070      9.509444
min        0.003000      0.114000      0.000000     16.000000      5.000000
25%        4.360750     38.028500      0.633000     87.000000     13.357750
50%        6.026000     48.142000      0.800500    103.000000     21.455500
75%        7.715250     58.258500      0.969000    121.000000     29.688250
max       16.559000    103.016000      1.832000    231.000000     37.998000

           humidity    wind_speed
count  18000.000000  18000.000000
mean      57.714351      5.283910
std       18.844908      2.741712
min       25.002000      0.500000
25%       41.320000      2.937000
50%       57.847000      5.297000
75%       74.234750      7.662000
max       89.997000      9.999000

In [35]:
# indexing and selecting data
# selecting columns
df["city"]
df[["city", "aqi"]] # case sensitive values

# selecting rows
# label based
df.loc[0]
df.loc[0:2] # end idx is inclusive

# index based
df.iloc[0]
df.iloc[0:2] # end idx is exclusive

# select rows and columns
df.loc[0, "aqi"] # returns a single (scalar) value
df.loc[0, ["city", "aqi"]] # returns multiple columns for row 0 
df.loc[0:2, ["city", "aqi"]] # returns rows 0 to 2 (inclusive) and selected columns (dataframe)
df.columns # shows column names, not numerical indices
df.iloc[0:3, [2, 11]] # selects rows 0, 1, 2 and columns at numerical positions 2 and 11
df.iloc[0:3, 2:5]

# select singular scalar values
df.at[0, "city"]
df.iat[0, 2]

# view
cities = df["city"] # creates a view/reference to the original column, not an independent copy
# cities[0] = "mumbai" # modifying this may also modify df["city"] because cities is linked to the original dataframe
cities = df["city"].copy() # create a copy when you plan to modify the data
cities[0] = "mumbai"
cities 
df["city"] # no change in the original data

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [39]:
# filtering data
df[(df["aqi"] > 100)]
df[(df["aqi"] > 100) & (df["temperature"] > 30)]
df[(df["aqi"] > 100) & (df["temperature"] < 30)]

# chaining
aqi_data = df[(df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi", "temperature"]]

# labels are preserved
aqi_data
aqi_data.iloc[0] # first row by position
aqi_data.loc[6] # row with label 6

           city  aqi  temperature
6      New York  155       36.729
7      New York  115       37.891
14     New York  121       34.481
17     New York  127       36.193
25     New York  113       31.289
...         ...  ...          ...
17947    Zurich  107       32.584
17950    Zurich  140       36.885
17975    Zurich  111       30.761
17976    Zurich  146       30.909
17991    Zurich  104       32.556

[2384 rows x 3 columns]

In [43]:
# filter data using query() method
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]
aqi_val = 100
df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]] # using python variables
# returns a copy
# for simplicity, we can always use the copy() method
aqi_data = df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]].copy()